version: 0.2

phases:
  install:
    commands:
      - npm install # Install dependencies using npm

  build:
    commands:
      - npm run build # Build the React app

artifacts:
  files:
    - '**/*' # Include all files and directories in the build output
  discard-paths: yes
